[package]
name = "crystal-server"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["debug"]
debug = ["dep:tracing", "dep:color-eyre", "dep:tracing-subscriber"]

[dependencies]
bstr = "1.9.0"
chrono = "0.4.33"
num-traits = "0.2"
num-derive = "0.4"
serde_json = "1.0.113"
integer-hasher = "0.1.1"
tokio = { version = "1.36", features = ["rt", "io-util", "io-std", "sync", "net", "full"] }
tracing = { version = "0.1.40", optional = true }
color-eyre = { version = "0.6.2", optional = true }
tracing-subscriber = { version = "0.3.18", optional = true }
